// Copyright (c) 2022 NetEase, Inc. All rights reserved.
// Use of this source code is governed by a MIT license that can be
// found in the LICENSE file.

import Foundation

enum NETeamUIKitSwiftUIConstants {
  static let moduleName = "NETeamUIKitSwiftUI"
  static let telemetryComponentName = "TeamUIKitSwiftUI"
  static let telemetryLanguage = "swiftui"
}

enum NETeamLocalizableKey {
  static let setting = "setting"
  static let mark = "mark"
  static let historicalRecord = "historical_record"
  static let sessionSetTop = "session_set_top"
  static let groupInfo = "group_info"
  static let discussInfo = "discuss_info"
  static let messageRemind = "message_remind"
  static let members = "members"
  static let discussMember = "discuss_mebmer"
  static let owner = "owner"
  static let teamOwner = "team_owner"
  static let manager = "manager"
  static let groupManager = "group_manager"
  static let teamName = "team_name"
  static let teamNick = "team_nick"
  static let teamIntroduce = "team_introduce"
  static let teamHeader = "team_header"
  static let teamId = "team_id"
  static let teamIntr = "team_intr"
  static let discussAvatar = "discuss_avatar"
  static let discussName = "discuss_name"
  static let discussIntro = "discuss_intro"
  static let teamManager = "team_manager"
  static let teamNoSpeak = "team_no_speak"
  static let teamMemberManager = "team_member_manager"
  static let addManager = "add_manager"
  static let transferOwner = "transfer_owner"
  static let joinTeam = "join_team"
  static let createTeam = "create_team"
  static let seniorTeam = "senior_team"
  static let createSeniorTeamNoti = "create_senior_team_noti"
  static let createTeamSuccess = "create_team_success"
  static let teamAvatar = "team_avatar"
  static let modifyHeadImage = "modify_headImage"
  static let defaultIcon = "default_icon"
  static let selectedMembers = "selected_members"
  static let selectMembers = "select_members"
  static let inputTeamId = "input_team_id"
  static let noTeamFind = "no_team_find"
  static let chat = "chat"
  static let sendTeamJoinApply = "send_team_join_apply"
  static let teamMemberLimitExceeded = "team_member_limit_exceeded"
  static let joinedTeamLimitExceeded = "joined_team_limit_exceeded"
  static let teamMemberSelect = "team_member_select"
  static let searchMember = "search_member"
  static let memberEmptyTip = "member_empty_tip"
  static let selectLimitTip = "select_limit_tip"
  static let teamMemberRemove = "team_member_remove"
  static let removeMemberTip = "remove_member_tip"
  static let removeFailed = "remove_failed"
  static let inviteMember = "invite_member"
  static let inviteMemberUnavailable = "invite_member_unavailable"
  static let removeManagerTitle = "remove_manager_title"
  static let removeManagerTip = "remove_manager_tip"
  static let maxManagersTip = "max_managers_tip"
  static let memberSelectNoMember = "member_select_no_member"
  static let manageTeam = "manage_team"
  static let manageManager = "manage_manger"
  static let whoEditTeamInfo = "who_edit_team_info"
  static let whoEditUserInfo = "who_edit_user_info"
  static let whoAtAll = "who_at_all"
  static let whoCanTopMessage = "who_can_top_message"
  static let teamAll = "team_all"
  static let teamOwnerAndManager = "team_owner_and_manager"
  static let invitationAcceptanceRequirement = "invitation_acceptance_requirement"
  static let invitationAcceptanceRequirementDesc = "invitation_acceptance_requirement_desc"
  static let requireVerificationToJoin = "require_verification_to_join"
  static let requireVerificationToJoinDesc = "require_verification_to_join_desc"
  static let remind = "remind"
  static let leaveTeam = "leave_team"
  static let dismissTeam = "dismiss_team"
  static let leaveDiscuss = "leave_discuss"
  static let quitTeamChat = "quit_team_chat"
  static let dissoluteTeamChat = "dissolute_team_chat"
  static let quitDiscussChat = "quit_discuss_chat"
  static let save = "save"
  static let noPermissionTip = "no_permission_tip"
  static let spaceNotSupport = "space_not_support"
  static let networkError = "network_error"
  static let teamNotExist = "team_not_exist"
  static let teamHasBeenRemoved = "team_has_been_removed"
  static let failedOperation = "failed_operation"
  static let loading = "loading"
  static let emptyTeam = "empty_team"
  static let search = "search"
  static let noResult = "no_result"
  static let noManagerMember = "no_manager_member"
  static let chatBanned = "chat_banned"
  static let avatarDeferred = "avatar_deferred"
  static let avatarSelected = "avatar_selected"
}
